### ISSUE TITLE
Won't install pip

### ISSUE THREAD

**Issue by Driesvdb98** [lucashusted/pytrendex#1]

**Comment by lucashusted** [comment]
You need to be a little more specific here...

**Comment by Driesvdb98** [comment]
Hi Lucas,

Thank you for your reply. Pytrends now works on my laptop.
Here's a link to my problem, in case other people have the same issue: https://stackoverflow.com/questions/64859170/pytrendex-wont-install-pip-file-troubles-running

kind regards,
Dries Van den Bergh
